name: Serenno-Crimson
main: io.jayms.serenno.SerennoCrimson
authors: 
- jayms
version: 1.0.0
depend: [CivModCore, ProtocolLib, Serenno-Common, FastAsyncWorldEdit, Citizens]
commands:
    duel:
        usage: /duel <player-name>
        description: Open duel GUI against a player.
        min-args: 1
        max-args: 1
        player-only: true
    accept:
        usage: /accept <player-name>
        description: Accepts duel against a player.
        min-args: 1
        max-args: 1
        player-only: true
    tsm:
        usage: /tsm
        description: Toggle schematic mode.
        min-args: 0
        max-args: 0
        player-only: true
    duelbot:
        usage: /duelbot <bot-name>
        description: Duel a bot.
        min-args: 1
        max-args: 1
        player-only: true
    kiteditor:
        usage: /kiteditor
        description: Go to the kit editor.
        min-args: 0
        max-args: 0
        player-only: true
    spectate:
        usage: /spectate <player>
        description: Spectate other players.
        min-args: 1
        max-args: 1
        player-only: true
    lobby:
        usage: /lobby
        description: Teleport to the lobby.
        min-args: 0
        max-args: 0
        player-only: true
    spfree:
        usage: /spfree
        description: Free a spectator pearl.
        min-args: 0
        max-args: 0
        player-only: true
    spectp:
        usage: /spectp <to-spectate>
        description: Teleport to player while spectating
        min-args: 1
        max-args: 1
        player-only: true
