artillery:
  trebuchet:
    schematic: trebuchet.schematic
    width:
      right: 10
      left: 10
    length:
      forward: 11
      backward: 10
    height: 16
    pointOfRotation:
      horizontalOffset: 3
      verticalOffset: 14
    cooldown: 6000
    missile:
      bastionDamage: 5
      reinforcementDamage: 5
      playerDamage: 5
      impactRadius: 4
citadel:
  reinforcement:
    defaultWorld: world

